### ISSUE TITLE
NTR: Request for P03 Marine geomorphology

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P03#1]
<p><b>Term name (PrefLabel)</b><p>Marine geomorphology <p><b>Definition</b><p>Parameters describing the morphology, evolution and associated transport phenomena of both seafloor and coastal landforms and features. Seafloor features may include bedforms, seamounts and ridges. Coastal features may include beaches and dunes. <p>

**Comment by danibodc** [comment]
Associated with https://github.com/nvs-vocabs/P01/issues/215

**This will be mapped to:**
P08 Marine geology: http://vocab.nerc.ac.uk/collection/P08/current/DS04/
P02 Coastal geomorphology: http://vocab.nerc.ac.uk/collection/P02/current/COGE/
P02 Seabed geomorphology: **New to be created ** (https://github.com/nvs-vocabs/P02/issues/11)

**Comment by gwemon** [comment]
Code GMAR added to P03 and queued for publication on the NVS.

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/P03/current/GMAR/
